accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.loginView, name="login"),
    path('register/', views.registerView, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('user/<int:id>/<str:tab>/', views.userView, name='user'),
    path('settings/<str:tab>/', views.settingsView, name='settings'),
    
    path('edit-profile/<int:id>/', views.editProfile, name='edit-profile'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.homePage, name='home'),
    path('create-post/', views.createPost, name='create-post'),
    path('detail-post/<int:id>/', views.detailPost, name='detail-post'),
    path('edit-post/<int:id>/', views.editPost, name='edit-post'),
    path('delete-post/<int:id>/', views.deletePost, name='delete-post'),
    path('update-vote-post/<int:id>/', views.updateVotePost, name='update-vote-post'),
    path('save-post/<int:id>/', views.savePost, name='save-post'),
    
    path('create-comment/<int:id>/', views.createComment, name='create-comment'),
    path('edit-comment/<int:id>/', views.editComment, name='edit-comment'),
    path('delete-comment/<int:id>/', views.deleteComment, name='delete-comment'),
    path('update-vote-comment/<int:id>/', views.updateVoteComment, name='update-vote-comment'),
    
    path('get-search-results/', views.getSearchResults, name='get-search-results'),
]

postbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify

# Create your models here.

# returns the objects that have not been deleted
# removes the necessary step to include is_deleted=False in each of our query (madami yun taena so this saves time)
class SoftDeleteManager(models.Manager):
    
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)

# to keep track of the deleted comments. For the replies to retain in the template
class SoftDeleteModel(models.Model):
    
    is_deleted          = models.BooleanField(default=False)
    
    objects             = SoftDeleteManager() # for reverse relationships
    
    # as a replacement from the usual 'Model.objects.all() -> Model.all_objects.all()'
    # this will also include the objects that have been soft deleted
    all_objects         = models.Manager() 
    
    def soft_delete(self):
        self.is_deleted = True
        self.save()
        
    def restore(self):
        self.is_deleted = False
        self.save()

    class Meta:
        abstract = True

# create our models as subclasses of SoftDeleteModel to grant them the ability to be soft-deleted 
class Post(SoftDeleteModel):
    
    user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title               = models.CharField(max_length=255)
    body                = models.CharField(max_length=955, null=True, blank=True)
    date_posted         = models.DateTimeField(auto_now_add=True)
    image               = models.ImageField(upload_to='images', blank=True, null=True)
    slug                = models.SlugField(default="", max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
          
    def get_likes(self):
        try:
            post = self.post_likes.get(post=self.id)
            if self.user.user_likes.filter(users=self.user).exists():
                return post.users.all().count()
            
            # when users unliked an already liked post, 
            # this will just return the number of users (without loggedin user) that have liked the post
            else:
                return post.users.all().count()
        except:
            
            return 0 
       
    
    def get_dislikes(self):
        
        try:
            post = self.post_dislikes.get(post=self.id)
            if self.user.user_likes.filter(users=self.user).exists():
                return post.users.all().count()
            
            # when users unliked an already liked post, 
            # this will just return the number of users (without loggedin user) that have liked the post
            else:
                return post.users.all().count()
        except:
            
            return 0 

class Comment(SoftDeleteModel):
    
    main_post           = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    reply               = models.ForeignKey('Comment', default="", on_delete=models.SET_DEFAULT, null=True, related_name='replies') # to be used in a nested comment thread
    user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body                = models.CharField(max_length=955)
    image               = models.ImageField(default='images', blank=True, null=True)
    date_posted         = models.DateTimeField(auto_now_add=True, null=True)
    comment_level       = models.IntegerField(null=True, blank=True)
    is_edited           = models.BooleanField(default=False, null=True, blank=True)
    
    # override the __init__ method of models.Model so that you can keep a copy of the original value
    __original_name = None
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_name = self.body
        
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        
        # making sure that the original value is not empty. 
        # The init method does not run when obj of a class is created despite it being a well known fact... at least for me
        if self.body != self.__original_name and self.__original_name != "":
            self.is_edited = True
        
        super().save(force_insert, force_update, *args, **kwargs) # Call the "real" save() method
        self.__original_name = self.body
            
    
    def __str__(self):
        return f'{self.user.first_name} replying to {self.main_post.title} content: {self.body}'
    
    # By making use of reply_id, we avoid loading the reply model object if it exists, which can lead to an N+1 problem
    @property
    def is_reply(self):
        return self.reply is not None
    
    @property
    def get_reply(self):
        return self.reply
    
    # if true, then we can identify if it is a nested comment or not.
    @property
    def has_replies(self):
        if self.is_deleted == True or self.is_deleted == False:
            return self.replies.exists()
        else:
            return self.replies.DoesNotExist
    
    # gets all replies related to the object that called it
    @property
    def get_replies(self):
        
        #  this will lead to an O(n) problem for larger scale comment threads
        replies = []
        for obj in Comment.all_objects.filter(main_post=self.main_post):
            if (obj.is_deleted or obj.is_deleted == False) and obj.reply == self:
                replies.append(obj)
        
        return replies
    
    
    def get_likes(self):
        
        try:
            comment = self.comment_likes.get(comment=self.id)
            if self.user.user_likes.filter(user=self.user).exists():
                
                return comment.users.all().count()
            
            else:
                return comment.users.all().count()
        except:
            return 0
        
    
    def get_dislikes(self):
        
        try:
            comment = self.comment_dislikes.get(comment=self.id)
            if self.user.user_likes.filter(user=self.user).exists():
                
                return comment.users.all().count()
            
            else:
                return comment.users.all().count()
        except:
            return 0
        
    # to retrieve comment user's profile photo
    @property
    def get_photo_url(self):
        
        if self.user.profile_pic and hasattr(self.user.profile_pic, 'url'):
            return self.user.profile_pic.url
        else:
            return "/static/images/profile/images/xianyun.jpg"
    
class LikeModel(SoftDeleteModel):
    
    users               = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_likes')
    post                = models.ForeignKey(Post, related_name='post_likes', null=True, blank=True, on_delete=models.SET_NULL)
    comment             = models.ForeignKey(Comment, related_name='comment_likes', null=True, blank=True, on_delete=models.SET_NULL)
    
    
    def __str__(self):
        if self.post:
            return f'liking post: {self.post.title}'
        elif self.comment:
            return f'liking comment: {self.comment.body}'
        else:
            return f'deleted post | comment'
    
class DislikeModel(SoftDeleteModel):
    
    users               = models.ManyToManyField(settings.AUTH_USER_MODEL)
    post                = models.ForeignKey(Post, related_name='post_dislikes', null=True, blank=True, on_delete=models.SET_NULL)
    comment             = models.ForeignKey(Comment, related_name='comment_dislikes', null=True, blank=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        if self.post:
            return f'disliking post: {self.post.title}'
        elif self.comment:
            return f'disliking comment: {self.comment.body}'
        else:
            return f'deleted post | comment'
        

class SavedPostsModel(SoftDeleteModel):
    
    users               = models.ManyToManyField(settings.AUTH_USER_MODEL)
    post                = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'saved post: {self.post.title}'
    

class Notification(models.Model):
    
    sender              = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sender', null=True, blank=True)
    receiver            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='receiver', null=True, blank=True)
    notif_type          = models.CharField(max_length=255, null=True, blank=True)
    is_read             = models.BooleanField(default=False, null=True, blank=True)
    message             = models.CharField(max_length=355, null=True, blank=True)
    date_added          = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.message
    
class Clients(models.Model):
    
    channel_name        = models.CharField(max_length=955, null=True, blank=True)
    
    
    
      

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Account
from home.models import Post, Comment, SavedPostsModel, LikeModel, DislikeModel
from .forms import RegisterModelForm, LoginModelForm, EditProfileForm

# Create your views here.
def loginView(request):
    form = LoginModelForm()
    
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        email=request.POST['email']
        password = request.POST['password']
        try: 
            user = get_object_or_404(Account, email=email)
            print(user.username)
        except:
            messages.error(request, 'Account does not exist', extra_tags='login')
        try:
            # THIS IS VERY MISLEADING POTANGINAAAAAAAAAAAAAAAAAAAAAAAAAA
            # since the username field is set to email, USE THAT INSTEAD TO PASS IN THE USERNAME PARAM
            user = authenticate(username=email, password=password)
            login(request, user)
            return redirect('home')
        except:
            messages.error(request, 'Credential Error', extra_tags='login')
            return redirect('login')
        
    context = {'login_form': form}
    
    return render(request, 'accounts/login.html', context)

def registerView(request):
    
    form = RegisterModelForm()
    context = {'reg_form': form}
   
    if request.method == 'POST':
        # add password authentication
        form = RegisterModelForm(request.POST)
        
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password1 = request.POST['password1']
        
        try:
            email_user = get_object_or_404(Account, email=email)
        except:
            email_user = None
            
        try:
            username = get_object_or_404(Account, username=username)
        except:
            username = None
            
        if email_user is not None:
            context['message'] = 'Email already exists'
            messages.error(request, 'Email already exists', extra_tags='register')
            return render(request, 'accounts/register.html', context)
        
        if username is not None:
            messages.error(request, 'Username is already taken', extra_tags='register')
            return render(request, 'accounts/register.html', context)
        
        if password != password1:
            messages.error(request, "Passwords don't match", extra_tags='register')
            return render(request, 'accounts/register.html', context)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Register Successfull! You may enter your credentials', extra_tags='login')
            return redirect('login')

    return render(request, 'accounts/register.html', context)

def logoutView(request):
    
    logout(request)
    
    return redirect('login')


@login_required(login_url='login')
def userView(request, id, tab):
    
    context = {}
    
    try:
        user = get_object_or_404(Account, id=id)
        context['user'] = user
        
        if tab == 'posts':
            user_posts = Post.objects.filter(user=user).order_by('-date_posted')
            context['user_posts'] = user_posts
            
        elif tab == 'comments':
            user_comments = Comment.objects.filter(user=user).order_by('-date_posted')
            context['user_comments'] = user_comments
        
        elif tab == 'saved':
            user_saved_posts = SavedPostsModel.objects.filter(users__id=user.id)
            context['user_saved_posts'] = user_saved_posts
        
        elif tab == 'upvoted':
            upvotes = LikeModel.objects.filter(users__id=user.id)
            context['upvotes'] = upvotes
            
        elif tab == 'downvoted':
            downvotes = DislikeModel.objects.filter(users__id=user.id)
            context['downvotes'] = downvotes
        
        return render(request, 'accounts/profile_page.html', context)
    except:
        context['message'] = 'Account does not exist'
        context['posts'] = Post.objects.all()
        return render(request, 'home/home.html',context)

@login_required(login_url='login')
def editProfile(request, id):
    
    context = {}
    form = EditProfileForm()
    try:
        user = get_object_or_404(Account, id=id)
        
    except:
        context['message'] = 'User does not exist'
        return redirect('home')
    
    if request.method == 'POST':
        print('post data: ',request.POST)
        form = EditProfileForm(request.POST, request.FILES, instance=user)
        
        if form.is_valid():
            profile = form.save(commit=False)
            
            if form.cleaned_data['bio']:
                profile.bio = form.cleaned_data['bio']
            
            if form.cleaned_data['profile_pic']:
                profile.profile_pic = form.cleaned_data['profile_pic']

            if form.cleaned_data['banner_pic']:
                profile.banner_pic = form.cleaned_data['banner_pic']
                
            profile.save()
            messages.success(request, 'Changes Saved', extra_tags='settings')
            return redirect('settings', 'profile')
        
    return JsonResponse(context)
    
    
    
@login_required(login_url='login')
def settingsView(request, tab):
    
    context = {}
    
    
    return render(request, 'accounts/settings.html', context)

accounts/templates/accounts/tabs/user_downvoted_posts.html
{% load custom_tags %}
{% load humanize %}


{% if downvotes %}

    {% for downvote in downvotes %}
        {% if downvote.post %}

            <div class="flex gap-2 w-full bg-gray-200 mb-6 relative   rounded-sm hover:border-black border-[1px] cursor-pointer mt-6">
                <div class="w-[50px] bg-gray-300 border-r-[1px] border-black px-4">
                    <div class=" flex flex-col items-center gap-2 py-2" id="vote_div">
                        <button class="flex items-center gap-2 text-xl hover:bg-gray-300 rounded-md " id="like_btn_parent">
                            {% is_liked downvote.post.id request.user as liked %}
                            {% if liked %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"  data-option="like"
                                    class="text-red-400" id="like_btn" data-post="{{ downvote.post.id }}">
                                    <path fill="currentColor" id="like_btn" data-post="{{ downvote.post.id }}"  data-option="like"
                                    d="M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625zM15 12h-1v8h-4v-8H6.081L12 4.601L17.919 12z"/>
                                </svg>    
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" 
                                    class="hover:text-red-400" id="like_post_btn" data-post="{{ downvote.post.id }}" data-option="like">
                                    <path fill="currentColor" id="like_btn" data-post="{{ downvote.post.id }}"  data-option="like"
                                    d="M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625zM15 12h-1v8h-4v-8H6.081L12 4.601L17.919 12z"/>
                                </svg>  
                            {% endif %}
                            <p id="like_count"> {{ downvote.post.get_likes }} </p>
                        </button>
                        <button class=" flex items-center gap-2 text-xl hover:bg-gray-300  rounded-md" id="dislike_btn_parent">
                            
                            {% is_disliked downvote.post.id request.user as disliked %}
                            {% if disliked %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" data-option="dislike"
                                class="text-blue-400" id="dislike_btn" data-post="{{ downvote.post.id }}">
                                <path fill="currentColor"  id="dislike_btn" data-post="{{ downvote.post.id }}" data-option="dislike"
                                d="M20.901 10.566A1.001 1.001 0 0 0 20 10h-4V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v7H4a1.001 1.001 0 0 0-.781 1.625l8 10a1 1 0 0 0 1.562 0l8-10c.24-.301.286-.712.12-1.059M12 19.399L6.081 12H10V4h4v8h3.919z"/>
                            </svg>
                            {% else %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" data-option="dislike"
                                class="hover:text-blue-400" id="dislike_btn" data-post="{{ downvote.post.id }}">
                                <path fill="currentColor"  id="dislike_btn" data-post="{{ downvote.post.id }}" data-option="dislike"
                                d="M20.901 10.566A1.001 1.001 0 0 0 20 10h-4V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v7H4a1.001 1.001 0 0 0-.781 1.625l8 10a1 1 0 0 0 1.562 0l8-10c.24-.301.286-.712.12-1.059M12 19.399L6.081 12H10V4h4v8h3.919z"/>
                            </svg>
                            {% endif %}
                            <p id="dislike_count"> {{ downvote.post.get_dislikes }} </p>
                        </button>
                        
                    </div>
                </div>
                <div class="py-4 w-full" id="post-div">
                    <input type="hidden" name="post_id" id="post_id" value="{{ downvote.post.id }}" class="post_id">
                    <p class="text-4xl pb-2">{{ downvote.post.title }}</p>
                    <p class="text-sm font-thin">Posted by: <a href="" class="hover:underline"> {{ downvote.post.user.username }} </a> {{ downvote.post.date_posted|naturaltime }}</p>
                    
                    {% if downvote.post.image %}

                        <img src="{{ downvote.post.image.url }}" alt="{{ downvote.post.image }}" class="object-fit max-h-[350px] max-w-[350px] mx-auto my-4">

                    {% endif %}

                    {% if downvote.post.body %}
                        <p class="pt-3">{{ downvote.post.body }}</p>
                    {% endif %}
                    
                    <div class="h-[50px] flex items-center justify-start pt-5 text-md relative" id="post_actions">
                        
                    
                        <div class="hover:bg-gray-300 flex items-center justify-center mx-2 gap-1 py-4 ">
                            <i class="fa fa-comments-o" aria-hidden="true"></i>
                            <p>{{ downvote.post.comment_set.all|length }} {{ downvote.post.comment_set.count|pluralize:"comment,comments" }}</p>
                        </div>

                        <button class="hover:bg-gray-300 flex items-center justify-center mx-2 gap-1 py-4 px-3 block" id="share_post_btn" value="{{ downvote.post.id }}" data-post-id="{{ downvote.post.id }}">
                            <i class="fa fa-share-square-o" aria-hidden="true" id="share_post_btn" data-post-id="{{ downvote.post.id }}"></i>
                            <p id="share_post_btn" data-post-id="{{ downvote.post.id }}">Share post</p>
                        </button>

                        <button class="hover:bg-gray-300 flex items-center justify-center mx-2 gap-1 py-4 px-2 block" id="save_post_btn_parent" value="{{ downvote.post.id }}" data-post-id="{{ downvote.post.id }}" data-user="{{ request.user }}">

                            <!-- wrapping the if condition within the text/p element will interfere with the event delegation. It wont detect this element. -->
                            {% is_saved downvote.post.id request.user as post_saved %}
                            {% if post_saved %}
                                <i class="fa fa-bookmark" aria-hidden="true" id="save_post_btn" data-post-id="{{ downvote.post.id }}" data-user="{{ request.user }}"></i>
                                <p class="save_text" id="save_post_btn" data-post-id="{{ downvote.post.id }}" data-user="{{ request.user }}">
                                    Remove from saved
                                </p>
                            {% else %}  
                                <i class="fa fa-bookmark-o" aria-hidden="true" id="save_post_btn" data-post-id="{{ downvote.post.id }}" data-user="{{ request.user }}"></i>
                                <p class="save_text" id="save_post_btn" data-post-id="{{ downvote.post.id }}" data-user="{{ request.user }}">
                                    Save
                                </p>
                            {% endif %}
                        </button>
                        
                    </div>
                </div>
            </div>
            
        {% endif %}

    {% endfor %}
{% else %}

    <p class="text-center">No posts found Browse <a href="{% url 'home' %}" class="underline decoration-2 decoration-sky-300">here</a> to find interisting posts!</p>

{% endif %}